name = "emby-ui" # Worker 的项目名称
main = "worker.js" # Worker 的主入口文件
compatibility_date = "2026-03-13" # 兼容性日期，用于指定使用的 Cloudflare 运行时版本

# KV 命名空间绑定声明 (KV Namespace Binding)
[[kv_namespaces]]
binding = "ENI_KV" # 代码中调用该 KV 的变量名
id = "a658024c3a3c49b99da0f2f4da8bda66" # 你的 KV 命名空间 ID (请替换为实际的 32 位字母数字组合)

# D1 数据库绑定声明 (D1 Database Binding)
[[d1_databases]]
binding = "DB" # 代码中调用该数据库的变量名
database_name = "emby" # 你的 D1 数据库的名称
database_id = "cdbaf4d4-909c-4eec-82af-438b3cbe0204" # 你的 D1 数据库 ID (请替换为实际的 UUID 格式)
